# Generated by Django 6.0.1 on 2026-02-04 22:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=50)),
                ('reputation_points', models.IntegerField(default=0)),
                ('max_level_reached', models.PositiveIntegerField(default=1)),
                ('daily_base_points', models.PositiveIntegerField(default=0)),
                ('daily_base_points_date', models.DateField(default=django.utils.timezone.localdate)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
