# Generated by Django 6.0.1 on 2026-02-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_listingimage_listing_contact_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='lesson_mode',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Присъствено'), ('online_and_in_person', 'Онлайн + присъствено')], default='online_and_in_person', max_length=24),
        ),
    ]
