# Generated by Django 6.0.1 on 2026-02-20 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_align_in_person_lesson_mode_value'),
        ('marketplace', '0006_alter_listing_lesson_mode'),
    ]

    operations = [
    ]
