# Generated by Django 6.0.1 on 2026-02-15

import apps.discussions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0002_postvote_commentvote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.discussions.models.comment_image_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.discussions.models.post_image_upload_to,
            ),
        ),
    ]
