# Generated by Django 6.0.1 on 2026-02-16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discussions", "0003_alter_post_and_comment_image_upload_to"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name="subject",
            name="theme_color",
            field=models.CharField(
                blank=True,
                default="",
                help_text="HEX цвят за плочката на началната страница (пример: #1DA1F2).",
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Въведете валиден HEX цвят (пример: #1DA1F2).",
                        regex="^#[0-9A-Fa-f]{6}$",
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="tile_image",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Път до static изображение за плочката (пример: img/subjects/math.svg).",
                max_length=255,
            ),
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ["sort_order", "name"]},
        ),
    ]
