# Generated by Django 6.0.1 on 2026-02-17 08:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussions', '0004_subject_tile_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='theme_color',
            field=models.CharField(blank=True, default='', help_text='HEX цвят за плочката на началната страница (пример: #1DA1F2).', max_length=7, validators=[django.core.validators.RegexValidator(message='Въведете валиден HEX цвят (пример: #1DA1F2).', regex='^#?[0-9A-Fa-f]{6}$')]),
        ),
    ]
